# Generated by Django 5.0.1 on 2024-01-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria_noticia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticias.categoria'),
        ),
    ]
